collections:
  section:
    output: true
defaults:
  - scope:
      path: ""
      type: "sections"
    values:
      layout: "section"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
domain: jgreen020.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://colwell.phd  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder